### ISSUE TITLE
As a Fleet Manager, I want to modify the licence classes and contact information of existing Safety Drivers.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#55]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] Given I’m in a role of a signed-in fleet manager, when I open the Safety Drivers’ management page, then the system shows a list of all the drivers.
- [x] Given I have a list with all driver, when I choose to edit one of the drivers, then the system allows me to edit the fields driving license type and email.
- [x] Given that I finish editing the fields, when I save the changes, I get a confirmation page.

**Comment by jonathanba** [comment]
46c455fb505a6e4170234b9c974014936896e569

**Comment by jonathanba** [comment]
f6e5e18d792eb2f4a485311b3fbef8f48e2e7528

**Comment by jonathanba** [comment]
a9fe3a4d6668039c8cdb97817623837c37f492d4

**Comment by jonathanba** [comment]
0ceb28ffefbc81b04c61c6b72af648114293fc8c

**Comment by jonathanba** [comment]
c65e00a04fdc6109448e0d0d194d510570b6d6dd

**Comment by jonathanba** [comment]
1fd9c43eef78bb7b08f0bdb406eb2a79e2d662b9
