### ISSUE TITLE
As a Fleet Manager, I want to filter the overview of the status of all Safety Drivers to make it easier to process.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#58]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] Given I’m in a role of a signed-in fleet manager, when I open the Safety Drivers’ management page, then the system shows a list of all the drivers.
- [x] Given that I have a list of all the drivers, when I browse to the top of the list, the the system shows a graph containing all the Safety Drivers grouped by Status.
- [ ] Given that I have a graph with all the drivers grouped by status, when I click on a status in the graph, the safety drivers are filtered based on the chosen status.

**Comment by jonathanba** [comment]
@andresest83 I'll implement the backend (REST and DB changes) so you can add the Angular parts

**Comment by jonathanba** [comment]
@andresest83 

I finished everything so far. Besides, I had a problem with the scope of the onClick function. We have to access our cars array. Using the anonymous function it seems to be not possible easily. I tried also a lambda function since there is a different scope. However, I couldn't solve it. Could you please have a look. I'm prejudiced after trying everything 🤕 . 

```
            options: {
                onClick: function oClick(e) {
                    const element = this.getElementAtEvent(e);

                    if (element.length) {
                        console.log(e);
                        this.cars.filter(car => car.status.toUpperCase() == element[0]._model.label.toUpperCase());
                    }
                }
            }
```

**Comment by clemenspeters** [comment]
@jonathanba is this ticket done?
