### ISSUE TITLE
As a Fleet Manager, I want to add new vehicles to the fleet.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#59]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] Given I’m in a role of a signed-in fleet manager, when I open the Vehicles management page, then the system gives me a New Vehicle option.
- [x] Given I’m in a role of a signed-in fleet manager, when I click the new vehicle option, then I can add the following information for a new driver: Model, Status (driving_empty, driving_full, maintenance, available, inactive), License.
- [x] Given I enter the information for a new vehicle when I save my changes, then the system shows a confirmation page.

**Comment by jonathanba** [comment]
9cd69cf937f6b20cd683ef0d2c504512a7c2d7c2

**Comment by jonathanba** [comment]
3eaa8142a4088c67e210290cd54c60053118b59d
