### ISSUE TITLE
As a Fleet Manager, I want to deactivate vehicles from the fleet.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#60]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] Given I’m in a role of a signed-in fleet manager, when I open the vehicles’ management page, then the system shows a list of all the vehicles.
- [ ] Given that I have a list with all the vehicles, when I choose to edit one vehicle, then the system allows me to change the status field to inactive.
- [x] Given that I finish editing the status field, when I save the changes, I get a confirmation page.

**Comment by jonathanba** [comment]
48b22f88f49affc66d849425808b002ce819fd5f
