### ISSUE TITLE
As a Fleet Manager, I want to view the entire fleet schedule.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#63]
**Details:**
In the FM web app, a fleet schedule view is required which shows an overview of all upcoming shifts across the entire fleet. This schedule view should clearly communicate the personal schedule of each driver and which vehicles they are assigned to. This schedule view should display all shifts within a user-defined 24-hour window.

**Tasks:**

- [x] Research available calendar libraries and frameworks
- [x] Design appropriate view layout
- [x] Create API endpoint which provides all assigned shifts
- [x] Create API endpoint which provides all assigned shifts of the next 24 hours
- [ ] Build prototype that shows the schedule for the next 24 hours
- [ ] Extend prototype to provide the ability to select and view the schedule of any 24-hour period 

**Acceptance criteria:**

- [x] API endpoint which provides all assigned shifts
- [x] API endpoint which provides all assigned shifts of any 24-hour period
- [ ] Fleet schedule view in the web app dynamically showing the upcoming shifts of all drivers for the next 24 hours
- [ ] Ability to select and view the schedule of any 24-hour period

**Comment by jonathanba** [comment]
@andresest83 we could use a calendar? You have any specific idea how to design it?

**Comment by jonathanba** [comment]
@tomcory Like we discussed. I'll create a new item and a new component for the navbar. You implement the calendar view then. For the calendar view, we can just call the Endpoint /api/schifts to get all shifts and load it then.

**Comment by jonathanba** [comment]
will finish the API endpoint later this day on post you the URL here

**Comment by jonathanba** [comment]
endpoint for full shifts only: api/shifts/full
