### ISSUE TITLE
As a Fleet Manager, I want to create new shifts for specific time slots in the fleet schedule.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#65]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] The fleet manager is presented with a new shift option in the Shifts management page.
- [x] The fleet manager can add the following information for a new Shift: Start time and End time.
- [x] The fleet manager can see a confirmation page after creating the new shift.

**Comment by jonathanba** [comment]
8b3135f5888ff23a1366f293a9154222e191812b

**Comment by jonathanba** [comment]
60851616f5c1d36c43f94d298385561496bebb9d

**Comment by jonathanba** [comment]
be9d9297d73d135525b516b6cf7072d9c9ef7e85
