### ISSUE TITLE
As a Fleet Manager, I want to assign vehicles to newly created shifts.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#67]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] Given I’m in a role of a signed-in fleet manager, when I open the Shifts management page, then the system shows a list of all the shifts.
- [x] Given I have a list of all the shifts, when I choose to edit a shift then the system shows a field named vehicle and I can choose one of the available vehicles.
- [x] Given that I choose a vehicle to cover the shift, when I click the save button then the system shows a confirmation page.

additional
- [x] only assign available driver
- [x] only assign available cars

**Comment by jonathanba** [comment]
48b22f88f49affc66d849425808b002ce819fd5f
